stages:
  train:
    cmd: python 
      /home/rteam1/Downloads/sd_dvc/stable_deffussion_mlops/General_Generative_Defect/multi_subject_SD/run_train.py
    deps:
    - General_Generative_Defect/multi_subject_SD/run_train.py
