stages:
  resize:
    cmd: python /home/rteam1/Downloads/sd_dvc/stable_deffussion_mlops/resize.py /home/rteam1/Downloads/sd_dvc/stable_deffussion_mlops/data/scratch_cv
    deps:
    - data/scratch_cv
    - resize.py
    params:
    - resize.img_type
    - resize.size
    outs:
    - data/resize
