stages:
  resize:
    cmd: python src/resize.py params.yaml
    deps:
    - data/scratch_cv
    - src/resize.py
    params:
    - resize.img_type
    - resize.input_dir
    - resize.output_dir
    - resize.size
    outs:
    - data/resized
  train:
    cmd: python src/train.py params.yaml
    deps:
    - data/resized
    - src/train.py
    params:
    - train.checkpointing_steps
    - train.dataset_name
    - train.instance_data_dir
    - train.instance_prompt
    - train.max_train_steps
    - train.num_train_epochs
    - train.pretrained_model_name_or_path
    - train.resolution
    - train.sample_batch_size
    - train.train_batch_size
    - train.trained_model_path
    outs:
    - results/scratch/scratch.ckpt
  inference:
    cmd: python src/inference.py params.yaml
    deps:
    - results/scratch/scratch.ckpt
    - src/inference.py
    params:
    - inference.input_checkpoint_path
    - inference.output_checkpoint_path
    outs:
    - results/scratch/trained_mode